name: peacegrows
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40325
title: I am where Peace Grows
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffffd'
    - '#423d37'
    - '#60a626'
    - '#9cd508'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
