name: peacegrows
favicon: null
layout_spectrum: 0.6282448109705001
typography_spectrum: 0.07904672436416149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27355211158283055
  lightness: 0.02568383770994842
  saturation: 0.09543082606978714
  rhythmicContrast: 0.582323748152703
purpose: []
